<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="resources\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <PackageReference Include="ImGui.Net" Version="1.91.6.1" />
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <PackageReference Include="rlImGui-cs" Version="3.2.0" />
  </ItemGroup>

</Project>
